/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Model;
import util.koneksi;

/**
 *
 * @author ASUS
 */
public class Transaksi extends javax.swing.JPanel {

    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
        tampil_combo();
    }
    koneksi koneksi = new koneksi();
    Controller cb = new Controller();
    Model mb = new Model();
    
    
    public void tampil_combo()
    {
        try {
        koneksi.KoneksiDatabase();
            
        String sql = "select menuid from tbl_menu order by menuid";      // disini saya menampilkan NIM, anda dapat menampilkan
        ResultSet res = koneksi.state.executeQuery(sql);                                // yang anda ingin kan
        
        while(res.next()){
            Object[] ob = new Object[3];
            ob[0] = res.getString(1);
            
            jComboBox1.addItem((String) ob[0]);
            jComboBox2.addItem((String) ob[0]);// fungsi ini bertugas menampung isi dari database
            jComboBox3.addItem((String) ob[0]);
            jComboBox4.addItem((String) ob[0]);
            jComboBox5.addItem((String) ob[0]);
            jComboBox6.addItem((String) ob[0]);
            jComboBox7.addItem((String) ob[0]);
            jComboBox8.addItem((String) ob[0]);
            jComboBox9.addItem((String) ob[0]);
        }
        res.close();
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
}
    
    public void tampil()
    {
        try {
        koneksi.KoneksiDatabase();
        String sql = "select nama, harga from tbl_menu where menuid='"+jComboBox1.getSelectedItem()+"'";  
        ResultSet res = koneksi.state.executeQuery(sql); 
        
        while(res.next()){
            Object[] ob = new Object[3];
            ob[0]=  res.getString(1);
            ob[1]= res.getString(2);
            
            jTextFieldNama.setText((String) ob[0]);
            jTextFieldHarga.setText((String) ob[1]);
        }
        res.close();
         
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }  
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldHasil1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextFieldHasil3 = new javax.swing.JTextField();
        jTextFieldHasil4 = new javax.swing.JTextField();
        jTextFieldHasil5 = new javax.swing.JTextField();
        jTextFieldHasil6 = new javax.swing.JTextField();
        jTextFieldHasil7 = new javax.swing.JTextField();
        jTextFieldHasil8 = new javax.swing.JTextField();
        jTextFieldTotalBayar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextFieldHarga2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNama6 = new javax.swing.JTextField();
        jTextFieldNama3 = new javax.swing.JTextField();
        jTextFieldHarga6 = new javax.swing.JTextField();
        jTextFieldHarga3 = new javax.swing.JTextField();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextFieldNama7 = new javax.swing.JTextField();
        jTextFieldHarga7 = new javax.swing.JTextField();
        jComboBox8 = new javax.swing.JComboBox<>();
        jTextFieldNama8 = new javax.swing.JTextField();
        jTextFieldNama4 = new javax.swing.JTextField();
        jTextFieldHarga4 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox<>();
        jTextFieldNama5 = new javax.swing.JTextField();
        jTextFieldHarga8 = new javax.swing.JTextField();
        jTextFieldHarga5 = new javax.swing.JTextField();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldNamaPembeli = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextFieldHarga = new javax.swing.JTextField();
        jTextFieldNama1 = new javax.swing.JTextField();
        jTextFieldHarga1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextFieldNama2 = new javax.swing.JTextField();
        jTextFieldTotal = new javax.swing.JTextField();
        jTextFieldTotal1 = new javax.swing.JTextField();
        jTextFieldTotal2 = new javax.swing.JTextField();
        jTextFieldTotal3 = new javax.swing.JTextField();
        jTextFieldTotal4 = new javax.swing.JTextField();
        jTextFieldTotal5 = new javax.swing.JTextField();
        jTextFieldTotal6 = new javax.swing.JTextField();
        jTextFieldTotal7 = new javax.swing.JTextField();
        jTextFieldTotal8 = new javax.swing.JTextField();
        jTextFieldHasil = new javax.swing.JTextField();
        jTextFieldHasil2 = new javax.swing.JTextField();

        jTextFieldHasil1.setText("0");
        jTextFieldHasil1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldHasil1MouseClicked(evt);
            }
        });
        jTextFieldHasil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHasil1ActionPerformed(evt);
            }
        });

        jButton1.setText("Hasil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldHasil3.setText("0");
        jTextFieldHasil3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldHasil3MouseClicked(evt);
            }
        });
        jTextFieldHasil3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHasil3ActionPerformed(evt);
            }
        });

        jTextFieldHasil4.setText("0");
        jTextFieldHasil4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldHasil4MouseClicked(evt);
            }
        });
        jTextFieldHasil4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHasil4ActionPerformed(evt);
            }
        });

        jTextFieldHasil5.setText("0");
        jTextFieldHasil5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldHasil5MouseClicked(evt);
            }
        });
        jTextFieldHasil5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHasil5ActionPerformed(evt);
            }
        });

        jTextFieldHasil6.setText("0");
        jTextFieldHasil6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldHasil6MouseClicked(evt);
            }
        });
        jTextFieldHasil6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHasil6ActionPerformed(evt);
            }
        });

        jTextFieldHasil7.setText("0");
        jTextFieldHasil7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldHasil7MouseClicked(evt);
            }
        });
        jTextFieldHasil7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHasil7ActionPerformed(evt);
            }
        });

        jTextFieldHasil8.setText("0");
        jTextFieldHasil8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldHasil8MouseClicked(evt);
            }
        });
        jTextFieldHasil8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHasil8ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("TOTAL BAYAR Rp.");

        jButton2.setText("transaksi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });

        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });

        jLabel2.setText("Yang di beli");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jLabel3.setText("Total Jumlah");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama Pembeli :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextFieldTotal.setText("0");
        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });

        jTextFieldTotal1.setText("0");

        jTextFieldTotal2.setText("0");

        jTextFieldTotal3.setText("0");

        jTextFieldTotal4.setText("0");
        jTextFieldTotal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotal4ActionPerformed(evt);
            }
        });

        jTextFieldTotal5.setText("0");

        jTextFieldTotal6.setText("0");

        jTextFieldTotal7.setText("0");

        jTextFieldTotal8.setText("0");

        jTextFieldHasil.setText("0");
        jTextFieldHasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldHasilMouseClicked(evt);
            }
        });
        jTextFieldHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHasilActionPerformed(evt);
            }
        });

        jTextFieldHasil2.setText("0");
        jTextFieldHasil2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldHasil2MouseClicked(evt);
            }
        });
        jTextFieldHasil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHasil2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldNama7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldHarga7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldNama6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldHarga6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldNama5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldHarga5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldNama4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldHarga4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldNama3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldHarga3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldNama2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldHarga2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldNama1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldNama8, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldHarga8, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldNama)
                                        .addComponent(jTextFieldNamaPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextFieldTotal7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldHasil7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextFieldTotal5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldHasil6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextFieldTotal6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldHasil5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextFieldTotal4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldHasil4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextFieldTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldHasil3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextFieldTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldHasil2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextFieldTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldHasil1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextFieldTotal8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldHasil8, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(87, 87, 87)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNamaPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHasil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHarga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNama2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHasil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHarga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNama3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHasil3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHarga4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNama4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHasil4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHarga5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNama5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotal6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHasil5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHarga6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNama6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHasil6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHarga7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNama7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotal7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHasil7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHarga8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNama8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotal8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHasil8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldHasil1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldHasil1MouseClicked
        // TODO add your handling code here:
        int hasil;
        int harga = Integer.parseInt(jTextFieldHarga1.getText());
        int total = Integer.parseInt(jTextFieldTotal2.getText());

        hasil = harga*total;
        jTextFieldHasil1.setText(""+hasil);
    }//GEN-LAST:event_jTextFieldHasil1MouseClicked

    private void jTextFieldHasil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHasil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHasil1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {
            int totalBayar;
            int hasil0 = Integer.parseInt(jTextFieldHasil2.getText());
            int hasil1 = Integer.parseInt(jTextFieldHasil.getText());
            int hasil2 = Integer.parseInt(jTextFieldHasil1.getText());
            int hasil3 = Integer.parseInt(jTextFieldHasil3.getText());
            int hasil4 = Integer.parseInt(jTextFieldHasil4.getText());
            int hasil5 = Integer.parseInt(jTextFieldHasil5.getText());
            int hasil6 = Integer.parseInt(jTextFieldHasil6.getText());
            int hasil7 = Integer.parseInt(jTextFieldHasil7.getText());
            int hasil8 = Integer.parseInt(jTextFieldHasil8.getText());

            totalBayar = hasil0 + hasil1 + hasil2 + hasil3 + hasil4 + hasil5 + hasil6 + hasil7 + hasil8;

            jTextFieldTotalBayar.setText(""+totalBayar);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "data kosong");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldHasil3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldHasil3MouseClicked
        // TODO add your handling code here:
        int hasil;
        int harga = Integer.parseInt(jTextFieldHarga3.getText());
        int total = Integer.parseInt(jTextFieldTotal3.getText());

        hasil = harga*total;
        jTextFieldHasil3.setText(""+hasil);
    }//GEN-LAST:event_jTextFieldHasil3MouseClicked

    private void jTextFieldHasil3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHasil3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHasil3ActionPerformed

    private void jTextFieldHasil4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldHasil4MouseClicked
        // TODO add your handling code here:
        int hasil;
        int harga = Integer.parseInt(jTextFieldHarga4.getText());
        int total = Integer.parseInt(jTextFieldTotal4.getText());

        hasil = harga*total;
        jTextFieldHasil4.setText(""+hasil);
    }//GEN-LAST:event_jTextFieldHasil4MouseClicked

    private void jTextFieldHasil4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHasil4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHasil4ActionPerformed

    private void jTextFieldHasil5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldHasil5MouseClicked
        // TODO add your handling code here:
        int hasil;
        int harga = Integer.parseInt(jTextFieldHarga5.getText());
        int total = Integer.parseInt(jTextFieldTotal6.getText());

        hasil = harga*total;
        jTextFieldHasil5.setText(""+hasil);
    }//GEN-LAST:event_jTextFieldHasil5MouseClicked

    private void jTextFieldHasil5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHasil5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHasil5ActionPerformed

    private void jTextFieldHasil6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldHasil6MouseClicked
        // TODO add your handling code here:
        int hasil;
        int harga = Integer.parseInt(jTextFieldHarga6.getText());
        int total = Integer.parseInt(jTextFieldTotal6.getText());

        hasil = harga*total;
        jTextFieldHasil6.setText(""+hasil);
    }//GEN-LAST:event_jTextFieldHasil6MouseClicked

    private void jTextFieldHasil6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHasil6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHasil6ActionPerformed

    private void jTextFieldHasil7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldHasil7MouseClicked
        // TODO add your handling code here:
        int hasil;
        int harga = Integer.parseInt(jTextFieldHarga7.getText());
        int total = Integer.parseInt(jTextFieldTotal7.getText());

        hasil = harga*total;
        jTextFieldHasil7.setText(""+hasil);
    }//GEN-LAST:event_jTextFieldHasil7MouseClicked

    private void jTextFieldHasil7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHasil7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHasil7ActionPerformed

    private void jTextFieldHasil8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldHasil8MouseClicked
        // TODO add your handling code here:
        int hasil;
        int harga = Integer.parseInt(jTextFieldHarga8.getText());
        int total = Integer.parseInt(jTextFieldTotal8.getText());

        hasil = harga*total;
        jTextFieldHasil8.setText(""+hasil);
    }//GEN-LAST:event_jTextFieldHasil8MouseClicked

    private void jTextFieldHasil8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHasil8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHasil8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            String nama = jTextFieldNamaPembeli.getText();
            String yangDiBeli = jTextField1.getText();
            String totalJumlah = jTextField2.getText();
            int totalBayar = Integer.parseInt(jTextFieldTotalBayar.getText());

            mb.setNamaPembeli(nama);
            mb.setYangDiBeli(yangDiBeli);
            mb.setTotalJumlah(totalJumlah);
            mb.setTotalBayar(totalBayar);

            cb.simpanTransaki(mb);

        } catch (Exception e) {
            System.err.println("" + e);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        jTextField1.setText(""+jComboBox1.getSelectedItem()+", "+jComboBox2.getSelectedItem()+", "+
            jComboBox3.getSelectedItem()+", "+jComboBox4.getSelectedItem()+", "+jComboBox5.getSelectedItem()+", "+
            jComboBox6.getSelectedItem()+", "+jComboBox7.getSelectedItem()+", "+jComboBox8.getSelectedItem()+", "+
            jComboBox9.getSelectedItem());
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:
        jTextField2.setText("" + jTextFieldHasil.getText() + ", " + jTextFieldHasil2.getText() + ", "
            + jTextFieldHasil1.getText() + ", " + jTextFieldHasil3.getText() + ", " + jTextFieldHasil4.getText() + ", "
            + jTextFieldHasil5.getText() + ", " + jTextFieldHasil6.getText() + ", " + jTextFieldHasil7.getText() + ", "
            + jTextFieldHasil8.getText() + ", ");
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        try {
            koneksi.KoneksiDatabase();
            String sql = "select nama, harga from tbl_menu where menuid='"+jComboBox3.getSelectedItem()+"'";
            ResultSet res = koneksi.state.executeQuery(sql);

            while(res.next()){
                Object[] ob = new Object[3];
                ob[0]=  res.getString(1);
                ob[1]= res.getString(2);

                jTextFieldNama2.setText((String) ob[0]);
                jTextFieldHarga2.setText((String) ob[1]);
            }
            res.close();

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
        try {
            koneksi.KoneksiDatabase();
            String sql = "select nama, harga from tbl_menu where menuid='"+jComboBox6.getSelectedItem()+"'";
            ResultSet res = koneksi.state.executeQuery(sql);

            while(res.next()){
                Object[] ob = new Object[3];
                ob[0]=  res.getString(1);
                ob[1]= res.getString(2);

                jTextFieldNama5.setText((String) ob[0]);
                jTextFieldHarga5.setText((String) ob[1]);
            }
            res.close();

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
        try {
            koneksi.KoneksiDatabase();
            String sql = "select nama, harga from tbl_menu where menuid='"+jComboBox6.getSelectedItem()+"'";
            ResultSet res = koneksi.state.executeQuery(sql);

            while(res.next()){
                Object[] ob = new Object[3];
                ob[0]=  res.getString(1);
                ob[1]= res.getString(2);

                jTextFieldNama6.setText((String) ob[0]);
                jTextFieldHarga6.setText((String) ob[1]);
            }
            res.close();

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        try {
            koneksi.KoneksiDatabase();
            String sql = "select nama, harga from tbl_menu where menuid='"+jComboBox4.getSelectedItem()+"'";
            ResultSet res = koneksi.state.executeQuery(sql);

            while(res.next()){
                Object[] ob = new Object[3];
                ob[0]=  res.getString(1);
                ob[1]= res.getString(2);

                jTextFieldNama3.setText((String) ob[0]);
                jTextFieldHarga3.setText((String) ob[1]);
            }
            res.close();

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
        try {
            koneksi.KoneksiDatabase();
            String sql = "select nama, harga from tbl_menu where menuid='"+jComboBox8.getSelectedItem()+"'";
            ResultSet res = koneksi.state.executeQuery(sql);

            while(res.next()){
                Object[] ob = new Object[3];
                ob[0]=  res.getString(1);
                ob[1]= res.getString(2);

                jTextFieldNama7.setText((String) ob[0]);
                jTextFieldHarga7.setText((String) ob[1]);
            }
            res.close();

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        try {
            koneksi.KoneksiDatabase();
            String sql = "select nama, harga from tbl_menu where menuid='"+jComboBox5.getSelectedItem()+"'";
            ResultSet res = koneksi.state.executeQuery(sql);

            while(res.next()){
                Object[] ob = new Object[3];
                ob[0]=  res.getString(1);
                ob[1]= res.getString(2);

                jTextFieldNama4.setText((String) ob[0]);
                jTextFieldHarga4.setText((String) ob[1]);
            }
            res.close();

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        // TODO add your handling code here:
        try {
            koneksi.KoneksiDatabase();
            String sql = "select nama, harga from tbl_menu where menuid='"+jComboBox9.getSelectedItem()+"'";
            ResultSet res = koneksi.state.executeQuery(sql);

            while(res.next()){
                Object[] ob = new Object[3];
                ob[0]=  res.getString(1);
                ob[1]= res.getString(2);

                jTextFieldNama8.setText((String) ob[0]);
                jTextFieldHarga8.setText((String) ob[1]);
            }
            res.close();

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        tampil();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        try {
            koneksi.KoneksiDatabase();
            String sql = "select nama, harga from tbl_menu where menuid='"+jComboBox2.getSelectedItem()+"'";
            ResultSet res = koneksi.state.executeQuery(sql);

            while(res.next()){
                Object[] ob = new Object[3];
                ob[0]=  res.getString(1);
                ob[1]= res.getString(2);

                jTextFieldNama1.setText((String) ob[0]);
                jTextFieldHarga1.setText((String) ob[1]);
            }
            res.close();

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    private void jTextFieldTotal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotal4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotal4ActionPerformed

    private void jTextFieldHasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldHasilMouseClicked
        // TODO add your handling code here:
        int hasil;
        int harga = Integer.parseInt(jTextFieldHarga.getText());
        int total = Integer.parseInt(jTextFieldTotal.getText());

        hasil = harga*total;
        jTextFieldHasil.setText(""+hasil);
    }//GEN-LAST:event_jTextFieldHasilMouseClicked

    private void jTextFieldHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHasilActionPerformed

    private void jTextFieldHasil2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldHasil2MouseClicked
        // TODO add your handling code here:
        int hasil;
        int harga = Integer.parseInt(jTextFieldHarga2.getText());
        int total = Integer.parseInt(jTextFieldTotal1.getText());

        hasil = harga*total;
        jTextFieldHasil2.setText(""+hasil);
    }//GEN-LAST:event_jTextFieldHasil2MouseClicked

    private void jTextFieldHasil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHasil2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHasil2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldHarga;
    private javax.swing.JTextField jTextFieldHarga1;
    private javax.swing.JTextField jTextFieldHarga2;
    private javax.swing.JTextField jTextFieldHarga3;
    private javax.swing.JTextField jTextFieldHarga4;
    private javax.swing.JTextField jTextFieldHarga5;
    private javax.swing.JTextField jTextFieldHarga6;
    private javax.swing.JTextField jTextFieldHarga7;
    private javax.swing.JTextField jTextFieldHarga8;
    private javax.swing.JTextField jTextFieldHasil;
    private javax.swing.JTextField jTextFieldHasil1;
    private javax.swing.JTextField jTextFieldHasil2;
    private javax.swing.JTextField jTextFieldHasil3;
    private javax.swing.JTextField jTextFieldHasil4;
    private javax.swing.JTextField jTextFieldHasil5;
    private javax.swing.JTextField jTextFieldHasil6;
    private javax.swing.JTextField jTextFieldHasil7;
    private javax.swing.JTextField jTextFieldHasil8;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldNama1;
    private javax.swing.JTextField jTextFieldNama2;
    private javax.swing.JTextField jTextFieldNama3;
    private javax.swing.JTextField jTextFieldNama4;
    private javax.swing.JTextField jTextFieldNama5;
    private javax.swing.JTextField jTextFieldNama6;
    private javax.swing.JTextField jTextFieldNama7;
    private javax.swing.JTextField jTextFieldNama8;
    private javax.swing.JTextField jTextFieldNamaPembeli;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextFieldTotal1;
    private javax.swing.JTextField jTextFieldTotal2;
    private javax.swing.JTextField jTextFieldTotal3;
    private javax.swing.JTextField jTextFieldTotal4;
    private javax.swing.JTextField jTextFieldTotal5;
    private javax.swing.JTextField jTextFieldTotal6;
    private javax.swing.JTextField jTextFieldTotal7;
    private javax.swing.JTextField jTextFieldTotal8;
    private javax.swing.JTextField jTextFieldTotalBayar;
    // End of variables declaration//GEN-END:variables
}
